
server:
  port:8080
spring:
  mvc:
    static-path-pattern: /res/**

  # 数据库配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Jincong@163.com
    type: com.alibaba.druid.pool.DruidDataSource

  # redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: jincong
    timeout: 2000
    jedis:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 3

  # 消息队列配置
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest



  # kafka配置
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: jincong
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


# mybatis配置
mybatis:
  type-aliases-package: com.jincong.springboot.domain
  mapper-locations: classpath:mapper/*.xml
  type-handlers-package: com.jincong.springboot.config

# 自定义注解
jc:
  hello:
    prefix: jincong
    suffix: 靳聪


my:
 kafka:
   broker: localhost:9092
   topic: TEST-TOPIC
   groupId: jincong1993
   client: bigger
   enable: N


