spring:
  mvc:
    static-path-pattern: /res/**

  redis:
    host: 127.0.0.1
    port: 6379
    password: jincong
    timeout: 2000
    jedis:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 3
